"""create posts table

Revision ID: 002fedbfbd97
Revises: ce5972bde8a2
Create Date: 2019-07-06 16:34:17.088528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002fedbfbd97'
down_revision = 'ce5972bde8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
