"""del email for users

Revision ID: 6fafa7d2aa89
Revises: dca089eab82d
Create Date: 2019-07-06 16:20:27.291948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fafa7d2aa89'
down_revision = 'dca089eab82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
