"""add column thumb in  posts table

Revision ID: 996e6dd03868
Revises: 002fedbfbd97
Create Date: 2019-07-07 14:00:52.667366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996e6dd03868'
down_revision = '002fedbfbd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_url')
    # ### end Alembic commands ###
